name: CI

# Controls when the workflow will run
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Atualizado para Node.js 20
      
    - name: Set up PHP with Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, dom, xml, zip, json
        coverage: none

    - name: Cache Composer packages
      uses: actions/cache@v3 # Atualizado para Node.js 20
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    - name: Install Composer dependencies
      run: |
        composer install --no-scripts --no-progress --prefer-dist
        composer dump-autoload --optimize --no-dev --classmap-authoritative
        
    - name: Fix permissions
      run: sudo chown -R $USER:$USER vendor
    
    - name: Install Node.js dependencies
      run: npm install
    
    - name: Execute PHPStan
      run: vendor/bin/phpstan analyse
