# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6

    - name: Cache Composer packages
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    - name: Install Composer dependencies
      run: |
        composer install --no-scripts --no-progress --prefer-dist
        composer dump-autoload --optimize --no-dev --classmap-authoritative
    
    - name: Installing Package.json
      run: npm install
      
    - name: Execute PHPSTAN
      run: vendor/bin/phpstan analyse
